//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace example { namespace SampleInterface {

public interface class ISampleInterfaceService
{
public:
    // Implement this function to handle calls to the Frobate method.
    Windows::Foundation::IAsyncOperation<SampleInterfaceFrobateResult^>^ FrobateAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ int32 interfaceMemberFoo);

    // Implement this function to handle calls to the Bazify method.
    Windows::Foundation::IAsyncOperation<SampleInterfaceBazifyResult^>^ BazifyAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ SampleInterfaceBar^ interfaceMemberBar);

    // Implement this function to handle calls to the Mogrify method.
    Windows::Foundation::IAsyncOperation<SampleInterfaceMogrifyResult^>^ MogrifyAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ SampleInterfaceBar^ interfaceMemberBar);

    // Implement this function to handle requests for the value of the Bar property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<SampleInterfaceGetBarResult^>^ GetBarAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the Bar property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<SampleInterfaceSetBarResult^>^ SetBarAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, byte value);

};

} } } 
