//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace example { namespace SampleInterface {

ref class SampleInterfaceSignals;

public interface class ISampleInterfaceSignals
{
    event Windows::Foundation::TypedEventHandler<SampleInterfaceSignals^, SampleInterfaceChangedReceivedEventArgs^>^ ChangedReceived;
};

public ref class SampleInterfaceSignals sealed : [Windows::Foundation::Metadata::Default] ISampleInterfaceSignals
{
public:
    // Calling this method will send the Changed signal to every member of the session.
    void Changed(_In_ bool interfaceMemberNew_value);

    // This event fires whenever the Changed signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<SampleInterfaceSignals^, SampleInterfaceChangedReceivedEventArgs^>^ ChangedReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<SampleInterfaceSignals^, SampleInterfaceChangedReceivedEventArgs^>^ handler) 
        { 
            return _ChangedReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<SampleInterfaceSignals^>(sender), safe_cast<SampleInterfaceChangedReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _ChangedReceived -= token; 
        } 
    internal: 
        void raise(SampleInterfaceSignals^ sender, SampleInterfaceChangedReceivedEventArgs^ args) 
        { 
            _ChangedReceived(sender, args);
        } 
    }

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallChangedReceived(_In_ SampleInterfaceSignals^ sender, _In_ SampleInterfaceChangedReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _ChangedReceived;

    alljoyn_interfacedescription_member m_memberChanged;
};

} } } 
